# -*- coding: utf-8 -*-
##############################################################################
#
#    SGR
#    Copyright (C) 2013 Grupo ADHOC
#    No email
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################


{   'active': False,
    'author': u'Grupo ADHOC',
    'category': u'base.module_category_knowledge_management',
    'demo_xml': [],
    'depends': [   u'account',
                   u'contacts',
                   u'product',
                   u'project',
                   u'mail',
                   u'stock'],
    'description': u'SGR. Sistema de Gestion de Registros',
    'init_xml': [],
    'installable': True,
    'license': 'AGPL-3',
    'name': u'SGR',
    'test': [],
    'update_xml': [   u'security/sgr_group.xml',
                      u'view/partner_document_presentation_view.xml',
                      u'view/ret_purpose_view.xml',
                      u'view/study_presentation_view.xml',
                      u'view/shipping_method_view.xml',
                      u'view/trademark_type_view.xml',
                      u'view/toxicological_class_view.xml',
                      u'view/ingredient_other_name_view.xml',
                      u'view/crop_view.xml',
                      u'view/physical_state_view.xml',
                      u'view/packaging_view.xml',
                      u'view/packaging_type_view.xml',
                      u'view/product_study_view.xml',
                      u'view/partner_role_in_registry_view.xml',
                      u'view/partner_view.xml',
                      u'view/ret_phase_view.xml',
                      u'view/publication_type_view.xml',
                      u'view/registry_category_view.xml',
                      u'view/component_registry_finality_view.xml',
                      u'view/publication_view.xml',
                      u'view/proposal_product_view.xml',
                      u'view/registry_process_view.xml',
                      u'view/environmental_class_view.xml',
                      u'view/ingredient_group_view.xml',
                      u'view/mode_of_action_view.xml',
                      u'view/study_method_view.xml',
                      u'view/communication_view.xml',
                      u'view/cqq_view.xml',
                      u'view/document_view.xml',
                      u'view/partner_document_view.xml',
                      u'view/dossier_document_view.xml',
                      u'view/study_view.xml',
                      u'view/tax_view.xml',
                      u'view/experimental_result_view.xml',
                      u'view/target_pests_view.xml',
                      u'view/product_view.xml',
                      u'view/sample_request_view.xml',
                      u'view/information_view.xml',
                      u'view/communication_type_view.xml',
                      u'view/lmr_view.xml',
                      u'view/state_registry_restriction_view.xml',
                      u'view/formulation_type_view.xml',
                      u'view/study_purpose_view.xml',
                      u'view/information_presentation_view.xml',
                      u'view/packaging_capacity_view.xml',
                      u'view/ingredient_function_view.xml',
                      u'view/proposal_view.xml',
                      u'view/application_mode_view.xml',
                      u'view/packaging_material_view.xml',
                      u'view/use_recommendation_view.xml',
                      u'view/document_move_view.xml',
                      u'view/agronomic_class_view.xml',
                      u'view/emergency_information_view.xml',
                      u'view/contract_view.xml',
                      u'view/component_registry_detail_view.xml',
                      u'view/product_in_ret_view.xml',
                      u'view/official_letter_view.xml',
                      u'view/information_category_view.xml',
                      u'view/registry_view.xml',
                      u'view/trademark_registry_view.xml',
                      u'view/state_registry_view.xml',
                      u'view/component_registry_view.xml',
                      u'view/technical_product_registry_view.xml',
                      u'view/laboratory_registry_view.xml',
                      u'view/ret_registry_view.xml',
                      u'view/formulated_product_registry_view.xml',
                      u'view/ingredient_view.xml',
                      u'view/ingredient_name_category_view.xml',
                      u'view/document_category_view.xml',
                      u'view/sgr_menuitem.xml',
                      u'data/partner_document_presentation_properties.xml',
                      u'data/ret_purpose_properties.xml',
                      u'data/study_presentation_properties.xml',
                      u'data/shipping_method_properties.xml',
                      u'data/trademark_type_properties.xml',
                      u'data/toxicological_class_properties.xml',
                      u'data/ingredient_other_name_properties.xml',
                      u'data/crop_properties.xml',
                      u'data/physical_state_properties.xml',
                      u'data/packaging_properties.xml',
                      u'data/packaging_type_properties.xml',
                      u'data/product_study_properties.xml',
                      u'data/partner_role_in_registry_properties.xml',
                      u'data/partner_properties.xml',
                      u'data/ret_phase_properties.xml',
                      u'data/publication_type_properties.xml',
                      u'data/registry_category_properties.xml',
                      u'data/component_registry_finality_properties.xml',
                      u'data/publication_properties.xml',
                      u'data/proposal_product_properties.xml',
                      u'data/registry_process_properties.xml',
                      u'data/environmental_class_properties.xml',
                      u'data/ingredient_group_properties.xml',
                      u'data/mode_of_action_properties.xml',
                      u'data/study_method_properties.xml',
                      u'data/communication_properties.xml',
                      u'data/cqq_properties.xml',
                      u'data/document_properties.xml',
                      u'data/partner_document_properties.xml',
                      u'data/dossier_document_properties.xml',
                      u'data/study_properties.xml',
                      u'data/tax_properties.xml',
                      u'data/experimental_result_properties.xml',
                      u'data/target_pests_properties.xml',
                      u'data/product_properties.xml',
                      u'data/sample_request_properties.xml',
                      u'data/information_properties.xml',
                      u'data/communication_type_properties.xml',
                      u'data/lmr_properties.xml',
                      u'data/state_registry_restriction_properties.xml',
                      u'data/formulation_type_properties.xml',
                      u'data/study_purpose_properties.xml',
                      u'data/information_presentation_properties.xml',
                      u'data/packaging_capacity_properties.xml',
                      u'data/ingredient_function_properties.xml',
                      u'data/proposal_properties.xml',
                      u'data/application_mode_properties.xml',
                      u'data/packaging_material_properties.xml',
                      u'data/use_recommendation_properties.xml',
                      u'data/document_move_properties.xml',
                      u'data/agronomic_class_properties.xml',
                      u'data/emergency_information_properties.xml',
                      u'data/contract_properties.xml',
                      u'data/component_registry_detail_properties.xml',
                      u'data/product_in_ret_properties.xml',
                      u'data/official_letter_properties.xml',
                      u'data/information_category_properties.xml',
                      u'data/registry_properties.xml',
                      u'data/trademark_registry_properties.xml',
                      u'data/state_registry_properties.xml',
                      u'data/component_registry_properties.xml',
                      u'data/technical_product_registry_properties.xml',
                      u'data/laboratory_registry_properties.xml',
                      u'data/ret_registry_properties.xml',
                      u'data/formulated_product_registry_properties.xml',
                      u'data/ingredient_properties.xml',
                      u'data/ingredient_name_category_properties.xml',
                      u'data/document_category_properties.xml',
                      u'data/partner_document_presentation_track.xml',
                      u'data/ret_purpose_track.xml',
                      u'data/study_presentation_track.xml',
                      u'data/shipping_method_track.xml',
                      u'data/trademark_type_track.xml',
                      u'data/toxicological_class_track.xml',
                      u'data/ingredient_other_name_track.xml',
                      u'data/crop_track.xml',
                      u'data/physical_state_track.xml',
                      u'data/packaging_track.xml',
                      u'data/packaging_type_track.xml',
                      u'data/product_study_track.xml',
                      u'data/partner_role_in_registry_track.xml',
                      u'data/partner_track.xml',
                      u'data/ret_phase_track.xml',
                      u'data/publication_type_track.xml',
                      u'data/registry_category_track.xml',
                      u'data/component_registry_finality_track.xml',
                      u'data/publication_track.xml',
                      u'data/proposal_product_track.xml',
                      u'data/registry_process_track.xml',
                      u'data/environmental_class_track.xml',
                      u'data/ingredient_group_track.xml',
                      u'data/mode_of_action_track.xml',
                      u'data/study_method_track.xml',
                      u'data/communication_track.xml',
                      u'data/cqq_track.xml',
                      u'data/document_track.xml',
                      u'data/partner_document_track.xml',
                      u'data/dossier_document_track.xml',
                      u'data/study_track.xml',
                      u'data/tax_track.xml',
                      u'data/experimental_result_track.xml',
                      u'data/target_pests_track.xml',
                      u'data/product_track.xml',
                      u'data/sample_request_track.xml',
                      u'data/information_track.xml',
                      u'data/communication_type_track.xml',
                      u'data/lmr_track.xml',
                      u'data/state_registry_restriction_track.xml',
                      u'data/formulation_type_track.xml',
                      u'data/study_purpose_track.xml',
                      u'data/information_presentation_track.xml',
                      u'data/packaging_capacity_track.xml',
                      u'data/ingredient_function_track.xml',
                      u'data/proposal_track.xml',
                      u'data/application_mode_track.xml',
                      u'data/packaging_material_track.xml',
                      u'data/use_recommendation_track.xml',
                      u'data/document_move_track.xml',
                      u'data/agronomic_class_track.xml',
                      u'data/emergency_information_track.xml',
                      u'data/contract_track.xml',
                      u'data/component_registry_detail_track.xml',
                      u'data/product_in_ret_track.xml',
                      u'data/official_letter_track.xml',
                      u'data/information_category_track.xml',
                      u'data/registry_track.xml',
                      u'data/trademark_registry_track.xml',
                      u'data/state_registry_track.xml',
                      u'data/component_registry_track.xml',
                      u'data/technical_product_registry_track.xml',
                      u'data/laboratory_registry_track.xml',
                      u'data/ret_registry_track.xml',
                      u'data/formulated_product_registry_track.xml',
                      u'data/ingredient_track.xml',
                      u'data/ingredient_name_category_track.xml',
                      u'data/document_category_track.xml',
                      u'workflow/study_workflow.xml',
                      u'workflow/state_registry_workflow.xml',
                      u'workflow/information_presentation_workflow.xml',
                      u'workflow/document_move_workflow.xml',
                      u'workflow/dossier_document_workflow.xml',
                      u'workflow/partner_document_workflow.xml',
                      u'workflow/communication_workflow.xml',
                      u'workflow/official_letter_workflow.xml',
                      u'workflow/registry_process_workflow.xml',
                      u'workflow/laboratory_registry_workflow.xml',
                      u'workflow/technical_product_registry_workflow.xml',
                      u'workflow/formulated_product_registry_workflow.xml',
                      u'workflow/ret_registry_workflow.xml',
                      u'workflow/component_registry_workflow.xml',
                      u'workflow/tax_workflow.xml',
                      u'workflow/contract_workflow.xml',
                      u'workflow/information_workflow.xml',
                      u'workflow/partner_document_presentation_workflow.xml',
                      u'workflow/study_presentation_workflow.xml',
                      u'workflow/proposal_workflow.xml',
                      u'workflow/sample_request_workflow.xml',
                      u'workflow/registry_workflow.xml',
                      u'workflow/trademark_registry_workflow.xml',
                      'security/ir.model.access.csv'],
    'version': u'7.0.1.2',
    'website': ''}

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
